### ISSUE TITLE
Adding a pgroonga index in a table with about 110K entries, fails.

### ISSUE THREAD

**Issue by ghevge** [pgroonga/pgroonga#298]
### What happend?

When I try to create a pgroonga index on a string column of a table with about 110K entries, after about 30 mins, the operation fails with the error below.

Any idea what is going on?

Index creation SQL:

```sql
CREATE INDEX p_model_idx ON products USING pgroonga(model);
```

Table DDL:

```sql
CREATE TABLE public.products (
	id uuid NOT NULL,
	category int2 NOT NULL,
	model varchar(100) NULL,
	isbn varchar(50) NULL,
	CONSTRAINT product_pkey PRIMARY KEY (id)
);
CREATE INDEX products_category_idx ON public.products USING btree (category);
CREATE INDEX products_id_idx ON public.products USING btree (id);
```

Error received:

```text
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [22023]: ERROR: pgroonga: failed to create table: <BuildingSources925700>: [object][register] failed to register a name: <BuildingSources925700>: <[table][add][dat] failed to add: #<key "BuildingSources
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:577)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:486)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:493)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:894)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3642)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4891)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: ERROR: pgroonga: failed to create table: <BuildingSources925700>: [object][register] failed to register a name: <BuildingSources925700>: <[table][add][dat] failed to add: #<key "BuildingSources
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
```

### How to reproduce it

Run `CREATE INDEX p_model_idx ON products USING pgroonga(model);`

### Expected behavior

No error

### Environment

pgroonga image: groonga/pgroonga:latest-alpine-15-slim

server version is : PostgreSQL 15.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit

**Comment by askdkc** [comment]
I might be wrong but, DBeaver might be the cause in this case.

Why don’t you just connect to your DB with psql command and run your create index SQL and to see how it goes?

**Comment by ghevge** [comment]
using psql  is not feasible for my prod env. I have to have it running with mybatis .

**Comment by askdkc** [comment]
@ghevge 

you should check `pgroonga.log` in your PDDATA folder. There might be a hint for what is causing this.

**Comment by ghevge** [comment]
@askdkc what is the exaxt path for this PDDATA  folder?

**Comment by kou** [comment]
It's a PostgreSQL's data directory.

**Comment by ghevge** [comment]
2023-03-16 18:59:24.278240|w|82: [DB Locked] time out(900000): io(base/16384/pgrn) collisions(900000/3)
2023-03-16 18:59:24.278300|e|82: grn_io_lock failed
2023-03-16 18:59:24.278334|e|82: [table][add][dat] failed to add: #<key "BuildingSources958469" table:#<dat (nil) key:(nil)>>
2023-03-16 18:59:24.278350|e|82: [object][register] failed to register a name: <BuildingSources958469>: <[table][add][dat] failed to add: #<key "BuildingSources958469" table:#<dat (nil) key:(nil)>>>

**Comment by askdkc** [comment]
@ghevge 

This might be a tuning issue. You should check `nofile` setting, change them and restart your server. See how it goes.

https://groonga.org/docs/reference/tuning.html#linux

**Comment by kou** [comment]
Your PGroonga data is broken. (Was your PostgreSQL crashed?) 
You need to recreate PGroonga data manually:

1. Stop your PostgreSQL
2. Remove all `pgrn*` files in `${PostgreSQL's data directory}/base/${Your database's OID}/`
3. Start your PostgreSQL
4. `REINDEX` all your PGroonga indexes

You can automate this by `pgroonga_crash_safer` module. See also: https://pgroonga.github.io/reference/crash-safe.html

**Comment by ghevge** [comment]
Adding the pgroonga_crash_safer configuration solved my problem! Thanks
