### ISSUE TITLE
SQL Error [0A000]: ERROR: pgroonga: [similar][text] similar search available only in index scan when doing joins

### ISSUE THREAD

**Issue by ghevge** [pgroonga/pgroonga#300]
### What happend?

When running the query below, I get a "pgroonga: [similar][text] similar search available only in index scan" error.

The products and search tables contain each about 280k records, while products_locations  contains 37 records.
LEFT JOIN works fine is just the JOIN and RIGHT JOIN that are failing with this error.

I've tried the solution mentioned on https://github.com/pgroonga/pgroonga/issues/163 but no luck.

`ALTER FUNCTION pgroonga_similar_text(text, text) COST 1000000;`

### How to reproduce it

Run the query:

```
SELECT p.id,
 p.category,
 p.rating,
 pl.id AS location_id,
 pl.latitude,
 pl.longitude,
 calculate_distance(pl.latitude, pl.longitude, 45.4906611, -73.4674481, 'K') AS distance
FROM products p 
JOIN (select * from products_locations where latitude <= 45.53563 AND latitude >= 45.4457 AND longitude <= -73.4033 AND longitude >= -73.53159) pl ON pl.product_id = p.id 
WHERE 1 = 1 
AND p.id IN ( SELECT product_id FROM search WHERE text &@* 'salt' AND locale = 'en' ) 
ORDER BY distance NULLS LAST 
LIMIT 10 OFFSET 0;
```

Search table DDL:

```
CREATE TABLE public."search" (
	id uuid NOT NULL,
	product_id uuid NOT NULL,
	locale varchar(20) NOT NULL,
	"text" text NULL,
	username varchar(255) NOT NULL,
	creation_time timestamp NOT NULL,
	update_time timestamp NOT NULL,
	CONSTRAINT search_pkey PRIMARY KEY (id),
	CONSTRAINT search_product_id_locale_key UNIQUE (product_id, locale),
	CONSTRAINT search_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE
);
CREATE INDEX search_locale_idx ON public.search USING btree (locale);
CREATE INDEX search_text_idx ON public.search USING pgroonga (text);
```

### Expected behavior

No error

### Environment

I am using docker image: groonga/pgroonga:latest-alpine-15-slim

### Additional context

Explain:

```
Limit  (cost=2511.15..2511.16 rows=1 width=111)
  ->  Sort  (cost=2511.15..2511.16 rows=1 width=111)
        Sort Key: (calculate_distance((products_locations.latitude)::double precision, (products_locations.longitude)::double precision, '45.4906611'::double precision, '-73.4674481'::double precision, 'K'::character varying))
        ->  Nested Loop  (cost=0.84..2511.14 rows=1 width=111)
              Join Filter: (products_locations.product_id = search.product_id)
              ->  Nested Loop  (cost=0.42..10.18 rows=1 width=119)
                    ->  Seq Scan on products_locations  (cost=0.00..1.74 rows=1 width=96)
                          Filter: ((latitude <= 45.53563) AND (latitude >= 45.4457) AND (longitude <= '-73.4033'::numeric) AND (longitude >= '-73.53159'::numeric))
                    ->  Index Scan using products_id_idx on products p  (cost=0.42..8.44 rows=1 width=23)
                          Index Cond: (id = products_locations.product_id)
              ->  Index Scan using search_product_id_locale_key on search  (cost=0.42..2500.70 rows=1 width=16)
                    Index Cond: ((product_id = p.id) AND ((locale)::text = 'en'::text))
                    Filter: (text &@* 'salt'::text)
```

Error:

```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [0A000]: ERROR: pgroonga: [similar][text] similar search available only in index scan
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:577)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:486)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:493)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:894)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3642)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4891)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: ERROR: pgroonga: [similar][text] similar search available only in index scan
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
```

**Comment by ghevge** [comment]
@kou do you have any idea how I can fix this ? Thanks!
