### ISSUE TITLE
ci macos: incorrect PostgreSQL library version referenced (PostgreSQL 14 instead of 15)

### ISSUE THREAD

**Issue by otegami** [pgroonga/pgroonga#522]
### What happened?

`pgroonga-benchmark` couldn't run because of the following error.
Because the `pg_ext.bundle` in `pg` gem is attempting to load the PostgreSQL 14 library (libpq.5.dylib), while PostgreSQL 15 is installed on the system.

ref: https://github.com/pgroonga/pgroonga/actions/runs/10190230760/job/28189596781

```console
pgroonga-benchmark is required: dlopen(/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/pg-1.5.7/lib/pg_ext.bundle, 0x0009): Library not loaded: /opt/homebrew/opt/postgresql@14/lib/postgresql@14/libpq.5.dylib
  Referenced from: <01D03C90-3C16-3457-B7D6-14AB32602E14> /Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/pg-1.5.7/lib/pg_ext.bundle
  Reason: tried: '/opt/homebrew/opt/postgresql@14/lib/postgresql@14/libpq.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/postgresql@14/lib/postgresql@14/libpq.5.dylib' (no such file), '/opt/homebrew/opt/postgresql@14/lib/postgresql@14/libpq.5.dylib' (no such file) - /Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/pg-1.5.7/lib/pg_ext.bundle
/Users/runner/hostedtoolcache/Ruby/3.3.4/arm64/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
/Users/runner/hostedtoolcache/Ruby/3.3.4/arm64/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/pg-1.5.7/lib/pg.rb:49:in `block in <module:PG>'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/pg-1.5.7/lib/pg.rb:37:in `block in <module:PG>'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/pg-1.5.7/lib/pg.rb:42:in `<module:PG>'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/pg-1.5.7/lib/pg.rb:6:in `<top (required)>'
/Users/runner/hostedtoolcache/Ruby/3.3.4/arm64/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
/Users/runner/hostedtoolcache/Ruby/3.3.4/arm64/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
/Users/runner/work/pgroonga/pgroonga/pgroonga-benchmark/lib/pgroonga-benchmark/config.rb:4:in `<top (required)>'
/Users/runner/hostedtoolcache/Ruby/3.3.4/arm64/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
/Users/runner/hostedtoolcache/Ruby/3.3.4/arm64/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
/Users/runner/work/pgroonga/pgroonga/test/helpers/sandbox.rb:609:in `require_pgroonga_benchmark'
/Users/runner/work/pgroonga/pgroonga/test/test-pgroonga-wal-resource-manager.rb:638:in `block in <class:PGroongaWALResourceManagerTestCase>'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/testcase.rb:871:in `run_test'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/testcase.rb:566:in `block (2 levels) in run'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/fixture.rb:276:in `block in create_fixtures_runner'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/fixture.rb:276:in `block in create_fixtures_runner'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/fixture.rb:276:in `block in create_fixtures_runner'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/fixture.rb:276:in `block in create_fixtures_runner'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/fixture.rb:276:in `block in create_fixtures_runner'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/fixture.rb:276:in `block in create_fixtures_runner'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/fixture.rb:276:in `block in create_fixtures_runner'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/fixture.rb:276:in `block in create_fixtures_runner'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/fixture.rb:276:in `block in create_fixtures_runner'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/fixture.rb:257:in `run_fixture'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/fixture.rb:292:in `run_setup'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/testcase.rb:564:in `block in run'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/testcase.rb:563:in `catch'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/testcase.rb:563:in `run'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/testsuite.rb:124:in `run_test'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/testsuite.rb:53:in `run'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/testsuite.rb:124:in `run_test'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/testsuite.rb:53:in `run'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/ui/testrunnermediator.rb:67:in `run_suite'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/ui/testrunnermediator.rb:45:in `block (2 levels) in run'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/ui/testrunnermediator.rb:102:in `with_listener'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/ui/testrunnermediator.rb:41:in `block in run'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/ui/testrunnermediator.rb:39:in `catch'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/ui/testrunnermediator.rb:39:in `run'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/ui/testrunner.rb:40:in `start_mediator'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/ui/testrunner.rb:25:in `start'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/autorunner.rb:469:in `block in run'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/autorunner.rb:525:in `change_work_directory'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/autorunner.rb:468:in `run'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/test-unit-3.6.2/lib/test/unit/autorunner.rb:66:in `run'
test/run-test.rb:24:in `<main>' [test: random crash(PGroongaWALResourceManagerTestCase)]
/Users/runner/work/pgroonga/pgroonga/test/helpers/sandbox.rb:615:in `rescue in require_pgroonga_benchmark'
```

### How to reproduce it

Re-run this job again
- https://github.com/pgroonga/pgroonga/actions/runs/10190230760/job/28189596781

### Expected behavior

Execute `pgroonga-benchmark` in CI environment like macOS Test(15) and Test(16).

### Environment

- OS: macOS
- OS Version: 14.5(arm64)
- PostgreSQL Version: 15.x, 16.x
- PGroonga Version: 3.2.1
- libgroonga Version: 14.0.6
   - https://pgroonga.github.io/reference/parameters/libgroonga-version.html

**Comment by otegami** [comment]
@kou advised me that setup-ruby caches used gems.
That's why the pg gem is referencing PostgreSQL 14, which we had installed previously.
ref: https://github.com/ruby/setup-ruby?tab=readme-ov-file#dealing-with-a-corrupted-cache

I'm trying to remove the cache here.
https://github.com/otegami/pgroonga/pull/4

**Comment by otegami** [comment]
PostgreSQL 15 自体への参照はできていそうだが、別の問題でうまく測定？ができていない。
Issue に上げた問題とは別の問題なので一旦別 Issue に切り出して対応するのでも良いかもしれない。
```
Failed to read bzcat input: Errno::EPIPE: Broken pipe
RuntimeError: entity expansion has grown too large
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/rexml-3.3.4/lib/rexml/parsers/baseparser.rb:560:in `block in unnormalize'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/rexml-3.3.4/lib/rexml/parsers/baseparser.rb:552:in `each'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/rexml-3.3.4/lib/rexml/parsers/baseparser.rb:552:in `unnormalize'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/rexml-3.3.4/lib/rexml/parsers/streamparser.rb:39:in `parse'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/red-datasets-0.1.7/lib/datasets/wikipedia.rb:51:in `block in each'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/red-datasets-0.1.7/lib/datasets/dataset.rb:78:in `block (2 levels) in extract_bz2'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/red-datasets-0.1.7/lib/datasets/dataset.rb:56:in `pipe'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/red-datasets-0.1.7/lib/datasets/dataset.rb:56:in `block in extract_bz2'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/red-datasets-0.1.7/lib/datasets/dataset.rb:55:in `pipe'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/red-datasets-0.1.7/lib/datasets/dataset.rb:55:in `extract_bz2'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/red-datasets-0.1.7/lib/datasets/wikipedia.rb:71:in `open_data'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/red-datasets-0.1.7/lib/datasets/wikipedia.rb:48:in `each'
test/run-test.rb:in `each'
#<Thread:0x00000001227184a0 /Users/runner/work/pgroonga/pgroonga/test/test-pgroonga-wal-resource-manager.rb:644 run> terminated with exception (report_on_exception is true):
/Users/runner/work/pgroonga/pgroonga/pgroonga-benchmark/lib/pgroonga-benchmark/record.rb:60:in `rescue in evaluate': Failed to evaluate: title: page.title (RuntimeError)
	from /Users/runner/work/pgroonga/pgroonga/pgroonga-benchmark/lib/pgroonga-benchmark/record.rb:55:in `evaluate'
	from /Users/runner/work/pgroonga/pgroonga/pgroonga-benchmark/lib/pgroonga-benchmark/record.rb:45:in `[]'
	from /Users/runner/work/pgroonga/pgroonga/pgroonga-benchmark/lib/pgroonga-benchmark/wikipedia-source.rb:35:in `block (2 levels) in generate_sqls'
	from /Users/runner/work/pgroonga/pgroonga/pgroonga-benchmark/lib/pgroonga-benchmark/wikipedia-source.rb:34:in `collect'
	from /Users/runner/work/pgroonga/pgroonga/pgroonga-benchmark/lib/pgroonga-benchmark/wikipedia-source.rb:34:in `block in generate_sqls'
	from <internal:numeric>:237:in `times'
	from /Users/runner/work/pgroonga/pgroonga/pgroonga-benchmark/lib/pgroonga-benchmark/wikipedia-source.rb:31:in `generate_sqls'
	from /Users/runner/work/pgroonga/pgroonga/pgroonga-benchmark/lib/pgroonga-benchmark/wikipedia-source.rb:16:in `block in each_sql'
	from /Users/runner/work/pgroonga/pgroonga/pgroonga-benchmark/lib/pgroonga-benchmark/wikipedia-source.rb:15:in `each'
	from /Users/runner/work/pgroonga/pgroonga/pgroonga-benchmark/lib/pgroonga-benchmark/wikipedia-source.rb:15:in `each_sql'
	from /Users/runner/work/pgroonga/pgroonga/pgroonga-benchmark/lib/pgroonga-benchmark/scenario-runner.rb:145:in `each_sql_job'
	from /Users/runner/work/pgroonga/pgroonga/pgroonga-benchmark/lib/pgroonga-benchmark/scenario-runner.rb:48:in `block (2 levels) in run'
	from /Users/runner/work/pgroonga/pgroonga/pgroonga-benchmark/lib/pgroonga-benchmark/scenario-runner.rb:45:in `each'
	from /Users/runner/work/pgroonga/pgroonga/pgroonga-benchmark/lib/pgroonga-benchmark/scenario-runner.rb:45:in `each_with_index'
	from /Users/runner/work/pgroonga/pgroonga/pgroonga-benchmark/lib/pgroonga-benchmark/scenario-runner.rb:45:in `block in run'
	from <internal:numeric>:237:in `times'
	from /Users/runner/work/pgroonga/pgroonga/pgroonga-benchmark/lib/pgroonga-benchmark/scenario-runner.rb:44:in `run'
	from /Users/runner/work/pgroonga/pgroonga/pgroonga-benchmark/lib/pgroonga-benchmark/processor.rb:30:in `block in process'
	from /Users/runner/work/pgroonga/pgroonga/pgroonga-benchmark/lib/pgroonga-benchmark/processor.rb:28:in `each'
	from /Users/runner/work/pgroonga/pgroonga/pgroonga-benchmark/lib/pgroonga-benchmark/processor.rb:28:in `process'
	from /Users/runner/work/pgroonga/pgroonga/test/test-pgroonga-wal-resource-manager.rb:654:in `block (2 levels) in <class:PGroongaWALResourceManagerTestCase>'
/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/rexml-3.3.4/lib/rexml/parsers/baseparser.rb:560:in `block in unnormalize': entity expansion has grown too large (RuntimeError)
	from /Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/rexml-3.3.4/lib/rexml/parsers/baseparser.rb:552:in `each'
	from /Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/rexml-3.3.4/lib/rexml/parsers/baseparser.rb:552:in `unnormalize'
	from /Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/rexml-3.3.4/lib/rexml/parsers/streamparser.rb:39:in `parse'
	from /Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/red-datasets-0.1.7/lib/datasets/wikipedia.rb:51:in `block in each'
	from /Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/red-datasets-0.1.7/lib/datasets/dataset.rb:78:in `block (2 levels) in extract_bz2'
	from /Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/red-datasets-0.1.7/lib/datasets/dataset.rb:56:in `pipe'
	from /Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/red-datasets-0.1.7/lib/datasets/dataset.rb:56:in `block in extract_bz2'
	from /Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/red-datasets-0.1.7/lib/datasets/dataset.rb:55:in `pipe'
	from /Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/red-datasets-0.1.7/lib/datasets/dataset.rb:55:in `extract_bz2'
	from /Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/red-datasets-0.1.7/lib/datasets/wikipedia.rb:71:in `open_data'
	from /Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/red-datasets-0.1.7/lib/datasets/wikipedia.rb:48:in `each'
	from test/run-test.rb:in `each'
```

**Comment by kou** [comment]
これはRed Datasetsの方をゴニョゴニョしないとダメっすね。

**Comment by otegami** [comment]
> これはRed Datasetsの方をゴニョゴニョしないとダメっすね。

ありがとうございます。
再現できる環境を用意して、ゴニョゴニョして PR 出してみます！

**Comment by otegami** [comment]
下記の問題に関しては、https://github.com/red-data-tools/red-datasets/pull/198 にて対応中！
https://github.com/pgroonga/pgroonga/issues/522#issuecomment-2262315503

**Comment by kou** [comment]
いや、pgroonga-benchmarkは`Datasets::Wikipedia`を使っている https://github.com/pgroonga/benchmark/blob/69517b9069939e0de01efff2d00c68a3e38632cd/lib/pgroonga-benchmark/wikipedia-source.rb#L11 ので https://github.com/red-data-tools/red-datasets/pull/198 だと直らないっす。

**Comment by otegami** [comment]
勘違いしていましたmm `Datasets::Wikipedia` も直そうとしていたので PR 作ったらリンクを更新します。
